### ISSUE TITLE
give this error when build a project in production mode 

### ISSUE THREAD

**Issue by neeraj-kritivity** [TypeCtrl/ngx-emoji-mart#315]
ERROR in ./node_modules/@ctrl/ngx-emoji-mart/fesm2015/ctrl-ngx-emoji-mart.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16599:21)
ERROR in ./node_modules/@ctrl/ngx-emoji-mart/fesm2015/ctrl-ngx-emoji-mart-ngx-emoji.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (D:\goblitz-frontend\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\goblitz-frontend\node_modules\typescript\lib\typescript.js:16599:21)

**Comment by scttcper** [comment]
whats in your package.json

**Comment by neeraj-kritivity** [comment]
"devDependencies": {
    "@angular-builders/custom-webpack": "^8.4.0",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-scss": "^2.0.0",
    "protractor": "~5.4.0",
    "tailwindcss": "^1.1.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }

**Comment by neeraj-kritivity** [comment]
"dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ctrl/ngx-emoji-mart": "^3.0.3",
    "@types/jquery": "^3.3.31",
    "flv.js": "^1.5.0",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "ngx-owl-carousel": "^2.0.7",
    "ngx-select-dropdown": "^1.3.1",
    "ngx-socket-io": "^3.0.1",
    "ngx-toastr": "^11.2.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "underscore": "^1.9.2",
    "zone.js": "~0.9.1"
  },

**Comment by scttcper** [comment]
Latest version requires angular 9. Check readme for the last version of 2.x to support angular 8
