### ISSUE TITLE
NullInjectorError: No provider for e!

### ISSUE THREAD

**Issue by hansifer** [TypeCtrl/ngx-emoji-mart#323]
We're seeing this runtime error when the emoji-mart component mounts in an Angular 8 project in prod mode:

```
ERROR NullInjectorError: StaticInjectorError(g)[ad -> e]: 
  StaticInjectorError(Platform: core)[ad -> e]: 
    NullInjectorError: No provider for e!
    at $.get (main.7aa74d82ba6166ce816f.js:1:533717)
    at main.7aa74d82ba6166ce816f.js:1:591211
    at e (main.7aa74d82ba6166ce816f.js:1:591586)
    at ia.get (main.7aa74d82ba6166ce816f.js:1:591737)
    at main.7aa74d82ba6166ce816f.js:1:591211
    at e (main.7aa74d82ba6166ce816f.js:1:591586)
    at ia.get (main.7aa74d82ba6166ce816f.js:1:591737)
    at Dd (main.7aa74d82ba6166ce816f.js:1:633014)
    at main.7aa74d82ba6166ce816f.js:1:633193
    at Td (main.7aa74d82ba6166ce816f.js:1:633387)
```

We're importing `PickerModule` and providing `EmojiSearch, EmojiFrequentlyService` in our module.

Any ideas?

**Comment by scttcper** [comment]
what's in package.json

**Comment by hansifer** [comment]
```
{
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@auth0/angular-jwt": "^2.1.2",
    "@ctrl/ngx-emoji-mart": "^3.0.4",
    "@ngx-translate/core": "^10.0.0",
    "@ngx-translate/http-loader": "^3.0.0",
    "@openid/appauth": "1.1.1",
    "ajv": "^6.10.2",
    "angular-cropperjs": "^1.0.1",
    "angular-jwt": "^0.1.11",
    "angular-oauth2-oidc": "^8.0.0",
    "angular2-uuid": "^1.1.1",
    "async-es": "^3.0.0",
    "autolinker": "^1.8.1",
    "autoprefixer": "^6.5.3",
    "cropperjs": "^1.5.5",
    "deepmerge": "^1.5.1",
    "graphql-request": "^1.8.2",
    "hammerjs": "2.0.8",
    "hellojs": "1.18.4",
    "json-file": "^0.1.0",
    "lamejs": "^1.2.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "ngx-clipboard": "^12.2.1",
    "ngx-device-detector": "1.3.6",
    "ngx-infinite-scroll": "^7.2.0",
    "ngx-linky": "~2.0.2",
    "ngx-logger": "^3.4.5",
    "ngx-long-press": "^0.0.1",
    "ngx-pipes": "^2.5.6",
    "nw-flash-trust": "^0.3.0",
    "rxjs": "^6.5.3",
    "rxjs-compat": "6.3.3",
    "ts-md5": "^1.2.6",
    "tslib": "^1.11.1",
    "webrtc": "^1.14.1",
    "xml-js": "^1.6.11",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular-devkit/build-ng-packagr": "~0.803.23",
    "@angular-devkit/core": "^8.3.23",
    "@angular-devkit/schematics": "8.3.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/platform-server": "^8.2.14",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jasmine": "^3.5.8",
    "@types/jasminewd2": "~2.0.4",
    "@types/lodash": "^4.14.138",
    "@types/node": "^10.17.17",
    "@types/readable-stream": "2.3.2",
    "@types/request": "^2.48.3",
    "@types/urijs": "^1.19.6",
    "@types/webrtc": "0.0.25",
    "base-href-webpack-plugin": "^2.0.0",
    "codelyzer": "^5.0.1",
    "common-tags": "^1.4.0",
    "crypto-js": "^3.1.9-1",
    "del": "^2.2.2",
    "handlebars": "^4.5.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "json-loader": "^0.5.4",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^3.1.0",
    "karma-jasmine-html-reporter": "^1.5.1",
    "karma-json-fixtures-preprocessor": "0.0.6",
    "karma-mocha-reporter": "^2.2.5",
    "karma-sonarqube-unit-reporter": "^0.0.21",
    "ng-packagr": "^5.7.1",
    "node-sass": "^4.13.1",
    "path": "^0.12.7",
    "protobufjs": "^6.8.6",
    "reconnecting-websocket": "^4.2.0",
    "run-sequence": "^2.2.1",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "ts-loader": "^6.2.1",
    "ts-node": "^7.0.1",
    "tsickle": "^0.37.0",
    "tslint": "^5.20.0",
    "tslint-eslint-rules": "^5.4.0",
    "typescript": "~3.5.3",
    "urijs": "^1.18.9",
    "url-parse": "^1.4.4",
    "wait-on": "^3.3.0"
  }
}
```

**Comment by scttcper** [comment]
https://github.com/TypeCtrl/ngx-emoji-mart#dependencies

> v2 requires angular 9

**Comment by hansifer** [comment]
Thanks! Apologies for overlooking that.
