### ISSUE TITLE
StaticInjectorError(AppModule)[ctrl_ngx_emoji_mart_CategoryComponent -> EmojiFrequentlyService]: 

### ISSUE THREAD

**Issue by SimonKomlos** [TypeCtrl/ngx-emoji-mart#337]
I'm having an issue in my angular app, I'm using `v3.0.4` of emoji-mart.

This is a brand new issue I didn't have previously, but I get the following error when trying to load it: 

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[ctrl_ngx_emoji_mart_CategoryComponent -> EmojiFrequentlyService]: 
  StaticInjectorError(Platform: core)[ctrl_ngx_emoji_mart_CategoryComponent -> EmojiFrequentlyService]: 
    NullInjectorError: No provider for EmojiFrequentlyService!
    at NullInjector.get (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:674054)
    at http://localhost:4200/main.ca53750b6edbc91605d8.js:1:689033
    at tryResolveToken (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:689713)
    at StaticInjector.get (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:689930)
    at http://localhost:4200/main.ca53750b6edbc91605d8.js:1:689033
    at tryResolveToken (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:689713)
    at StaticInjector.get (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:689930)
    at resolveNgModuleDep (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:724014)
    at NgModuleRef_.get (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:738204)
    at resolveDep (http://localhost:4200/main.ca53750b6edbc91605d8.js:1:745748)
```

I'm loading it in app.module like so:

```
import { PickerModule } from "@ctrl/ngx-emoji-mart";
import { EmojiModule } from '@ctrl/ngx-emoji-mart/ngx-emoji'
```

and in my `imports` as

```
    PickerModule,
    EmojiModule,
```

and then my html just looks like this:

```
<emoji-mart
(emojiClick)="addEmoji($event)" size="16" title="Pick module icon" emoji="point_up"></emoji-mart>
```

I'm loading it with the `MatBottomSheet` from Angular material.. Any idea why this might be happening?

**Comment by scttcper** [comment]
you should only need the `PickerModule` since it contains the emoji module https://github.com/TypeCtrl/ngx-emoji-mart/blob/master/src/lib/picker/picker.module.ts#L14

**Comment by SimonKomlos** [comment]
@scttcper I added that because it wasn't working without..

My package.json looks as follows in case that is helpful: 
```

{
  "name": "zogo-dashboard",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "~8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ctrl/ngx-emoji-mart": "3.0.4",
    "emoji-mart": "^3.0.0",
    "export-2-csv": "^1.0.6",
    "export-to-csv": "^0.2.1",
    "express": "^4.17.1",
    "hammerjs": "^2.0.8",
    "install": "^0.13.0",
    "json2csv": "^4.5.4",
    "moment": "^2.26.0",
    "npm": "^6.14.5",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.24",
    "@angular/cli": "~8.3.24",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

```

**Comment by scttcper** [comment]
the last version that works with angular v8 is 1.0.6 https://github.com/TypeCtrl/ngx-emoji-mart#dependencies

**Comment by SimonKomlos** [comment]
Thank you! Took me 3 hours to figure this out...

**Comment by scttcper** [comment]
most modules should warn you when you install them, but you can sometimes also find out by looking at peerDependencies
```
npm info @ctrl/ngx-emoji-mart peerDependencies
```
